### ISSUE TITLE
I am confused where are you getting this `comp_row`

### ISSUE THREAD

**Issue by atikhashmee** [niiknow/grapesjs-components-farmer#11]
https://github.com/niiknow/grapesjs-components-farmer/blob/7a186ca59fd3f4f5fd789140e1f2847bdcb9f460/src/blocks.js#L20

according to documentation, if you want to use block content as component that's when you can use `type` and provide component type id. 
but in your case I can see there is no where you created a component type called `comp_row` ? 

you mind describing a little bit please ?

**Comment by noogen** [comment]
All components are defined in the traits.js file here https://github.com/niiknow/grapesjs-components-farmer/blob/master/src/traits.js#L217

`comp_row` is defined here:  https://github.com/niiknow/grapesjs-components-farmer/blob/master/src/traits.js#L464

Therefore, you can extend it by providing the `type` that I've predefined in traits.js file.

**Comment by atikhashmee** [comment]
Thank you for your response. I was huge confused. but you made it clear man. thanks again
